Repository twatter-soen341/Twatter, pull requests merged in 2019-03, with the labels that each got.

#171 #148 Added posts to the search result page
  controllers/twatController.js
  controllers/user.js
  twatter-ui/src/app/feed/posts/post-list/post-list.component.html
  twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
  twatter-ui/src/app/search/search-bar/search-bar.component.ts
  twatter-ui/src/app/search/search-results/search-results.component.html
  twatter-ui/src/app/search/search-results/search-results.component.scss
  twatter-ui/src/app/search/search-results/search-results.component.ts
  twatter-ui/src/app/services/post.service.ts
  twatter-ui/src/styles.scss
Labels: Feature

#182 Functional Follow Button on Profile #101
  controllers/user.js
  routes/user.js
  twatter-ui/src/app/app-routing.module.ts
  twatter-ui/src/app/app.module.ts
  twatter-ui/src/app/feed/following-post/following-post.component.html
  twatter-ui/src/app/feed/following-post/following-post.component.scss
  twatter-ui/src/app/feed/following-post/following-post.component.ts
  twatter-ui/src/app/feed/posts/post-list/post-list.component.html
  twatter-ui/src/app/follow-button/follow-button.component.html
  twatter-ui/src/app/follow-button/follow-button.component.scss
  twatter-ui/src/app/follow-button/follow-button.component.ts
  twatter-ui/src/app/models/auth.model.ts
  twatter-ui/src/app/profile/sidebar/sidebar.component.html
  twatter-ui/src/app/profile/sidebar/sidebar.component.scss
  twatter-ui/src/app/profile/sidebar/sidebar.component.ts
  twatter-ui/src/app/services/follow-button.service.spec.ts
  twatter-ui/src/app/services/follow-button.service.ts
  twatter-ui/src/app/services/user.service.ts
Labels: Back-End, Front-End, Normal

#192 #150 #148 Modified Search result page to display posts and separated tabs
  twatter-ui/package.json
  twatter-ui/src/app/header/header.component.scss
  twatter-ui/src/app/search/search-bar/search-bar.component.html
  twatter-ui/src/app/search/search-bar/search-bar.component.scss
  twatter-ui/src/app/search/search-bar/search-bar.component.spec.ts
  twatter-ui/src/app/search/search-bar/search-bar.component.ts
  twatter-ui/src/app/search/search-results/search-results.component.html
  twatter-ui/src/app/search/search-results/search-results.component.scss
  twatter-ui/src/app/settings/settings.component.ts
Labels: Front-End, Normal

#196 Changed FollowingPost to FollowingPostComponent #60
  twatter-ui/src/app/app-routing.module.ts
Labels: Bug

#216 #173 added link to profile on comments
  twatter-ui/src/app/feed/posts/comment/comment.component.html
  twatter-ui/src/app/feed/posts/comment/comment.component.scss
  twatter-ui/src/app/feed/posts/comment/comment.component.ts
Labels: Front-End, Normal

#218 #132 Added backend routes to change password and email
  controllers/auth.js
  routes/auth.js
  routes/user.js
  tests/test.js
Labels: Back-End, Task

#228 #227 Added Bio to user model in backend
  controllers/auth.js
  controllers/user.js
  models/user.js
Labels: Back-End, Task

#230 #132 Updated controller to delete a user
  controllers/auth.js
Labels: Back-End

#231 #61 Changed post to twat
  controllers/twatController.js
  tests/test.js
  twatter-ui/src/app/app.module.ts
  twatter-ui/src/app/feed/following-post/following-post.component.ts
  twatter-ui/src/app/feed/posts/post-list/post-list.component.html
  twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
  twatter-ui/src/app/feed/twatline/twatline.component.html
  twatter-ui/src/app/feed/twatline/twatline.component.scss
  twatter-ui/src/app/feed/twatline/twatline.component.ts
  twatter-ui/src/app/feed/twats/comment/comment.component.html
  twatter-ui/src/app/feed/twats/comment/comment.component.scss
  twatter-ui/src/app/feed/twats/comment/comment.component.spec.ts
  twatter-ui/src/app/feed/twats/comment/comment.component.ts
  twatter-ui/src/app/feed/twats/twat-create/twat-create-dialog.component.html
  twatter-ui/src/app/feed/twats/twat-create/twat-create.component.html
  twatter-ui/src/app/feed/twats/twat-create/twat-create.component.scss
  twatter-ui/src/app/feed/twats/twat-create/twat-create.component.spec.ts
  twatter-ui/src/app/feed/twats/twat-create/twat-create.component.ts
  twatter-ui/src/app/feed/twats/twat-list/twat-edit-dialog.component.html
  twatter-ui/src/app/feed/twats/twat-list/twat-list.component.html
  twatter-ui/src/app/feed/twats/twat-list/twat-list.component.scss
  twatter-ui/src/app/feed/twats/twat-list/twat-list.component.spec.ts
  twatter-ui/src/app/feed/twats/twat-list/twat-list.component.ts
  twatter-ui/src/app/models/twat.model.ts
  twatter-ui/src/app/profile/profile.component.html
  twatter-ui/src/app/profile/profile.component.ts
  twatter-ui/src/app/search/search-bar/search-bar.component.html
  twatter-ui/src/app/search/search-bar/search-bar.component.ts
  twatter-ui/src/app/search/search-results/search-results.component.html
  twatter-ui/src/app/search/search-results/search-results.component.ts
  twatter-ui/src/app/services/post.service.ts
  twatter-ui/src/app/services/twat.service.ts
Labels: Improvement

#238 #61 Refactored posts to twats, removed unused ui elements and #226 calculation for twat score
  twatter-ui/src/app/app-routing.module.ts
  twatter-ui/src/app/components/feed/twats/twat-list/twat-list.component.html
  twatter-ui/src/app/components/header/header.component 2.html
  twatter-ui/src/app/components/header/header.component.html
  twatter-ui/src/app/components/profile/profile.component.html
  twatter-ui/src/app/components/profile/profile.component.ts
  twatter-ui/src/app/components/profile/sidebar/sidebar.component.html
  twatter-ui/src/app/components/profile/sidebar/sidebar.component.scss
  twatter-ui/src/app/components/profile/sidebar/sidebar.component.ts
  twatter-ui/src/app/components/search/search-results/search-results.component.html
  twatter-ui/src/app/components/search/search-results/search-results.component.ts
Labels: Improvement

#240 #239 Disabled comment button when there is no text
  twatter-ui/src/app/components/feed/twats/comment/comment.component.html
  twatter-ui/src/app/components/feed/twats/comment/comment.component.ts
  twatter-ui/src/app/components/feed/twats/twat-create/twat-create-dialog.component.html
Labels: Improvement

#244 Added bio
  twatter-ui/src/app/app-routing.module.ts
  twatter-ui/src/app/components/profile/profile.component.scss
  twatter-ui/src/app/components/profile/sidebar/sidebar.component.html
  twatter-ui/src/app/components/profile/sidebar/sidebar.component.scss
  twatter-ui/src/app/components/profile/sidebar/sidebar.component.ts
  twatter-ui/src/app/services/user.service.ts
Labels: Front-End, Normal, Task

#252 #224 Update to bio and sidebar
  twatter-ui/src/app/components/follow-button/follow-button.component.html
  twatter-ui/src/app/components/follow-button/follow-button.component.scss
  twatter-ui/src/app/components/header/header.component.scss
  twatter-ui/src/app/components/profile/profile.component.scss
  twatter-ui/src/app/components/profile/sidebar/sidebar.component.html
  twatter-ui/src/app/components/profile/sidebar/sidebar.component.scss
  twatter-ui/src/app/components/profile/sidebar/sidebar.component.ts
Labels: Front-End, Normal, Task

#259 #61 fixed position of header buttons
  twatter-ui/src/app/components/header/header.component.html
  twatter-ui/src/app/components/header/header.component.scss
Labels: Improvement
