Repository twatter-soen341/Twatter, pull requests merged in 2019-02, with the labels that each got.

#46 #35 Added backend authentication services
  controllers/authController.js
  middleware/passport.js
  models/user.js
  package.json
  routes/auth.js
  server.js
Labels: Feature

#67 #62 Added Guards for the Front-end endpoints
  controllers/authController.js
  middleware/passport.js
  models/user.js
  package.json
  routes/auth.js
  server.js
  twatter-ui/src/app/app-routing.module.ts
  twatter-ui/src/app/app.component.ts
  twatter-ui/src/app/guards/loggedIn.guard.ts
  twatter-ui/src/app/header/header.component.html
  twatter-ui/src/app/header/header.component.scss
  twatter-ui/src/app/header/header.component.ts
  twatter-ui/src/app/login/login.component.html
  twatter-ui/src/app/login/login.component.ts
Labels: Task

#68 #61 #25 Update post- and create-models UI
  twatter-ui/package.json
  twatter-ui/src/app/app.module.ts
  twatter-ui/src/app/feed/posts/post-create/post-create-dialog.component.html
  twatter-ui/src/app/feed/posts/post-create/post-create.component.scss
  twatter-ui/src/app/feed/posts/post-create/post-create.component.ts
  twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
  twatter-ui/src/app/models/post.model.ts
  twatter-ui/src/app/services/post.service.ts
Labels: Improvement

#73 #61 Made user create- and list- posts more user friendly
  package.json
  twatter-ui/src/app/feed/posts/post-create/post-create-dialog.component.html
  twatter-ui/src/app/feed/posts/post-create/post-create.component.html
  twatter-ui/src/app/feed/posts/post-create/post-create.component.scss
  twatter-ui/src/app/feed/posts/post-create/post-create.component.ts
  twatter-ui/src/app/feed/posts/post-list/post-list.component.html
  twatter-ui/src/app/feed/posts/post-list/post-list.component.scss
  twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
  twatter-ui/src/app/header/header.component.html
  twatter-ui/src/app/header/header.component.scss
  twatter-ui/src/app/header/header.component.ts
  twatter-ui/src/app/models/post.model.ts
  twatter-ui/src/app/services/post.service.ts
Labels: Improvement

#76 #75 Added user story issue templates
  .github/ISSUE_TEMPLATE/user-story-issue-template.md
Labels: Improvement

#77 #75 Update issue templates
  .github/ISSUE_TEMPLATE/user-story-issue-template.md
Labels: Improvement

#78 #72 Separated user and auth model
  controllers/auth.js
  controllers/user.js
  models/auth.js
  models/user.js
  routes/auth.js
  routes/user.js
  server.js
  twatter-ui/src/app/feed/posts/post-create/post-create.component.ts
  twatter-ui/src/app/header/header.component.ts
  twatter-ui/src/app/models/post.model.ts
  twatter-ui/src/app/services/auth.service.ts
  twatter-ui/src/app/services/user.service.spec.ts
  twatter-ui/src/app/services/user.service.ts
Labels: Back-End

#103 #81 #80 #25 Create, Edit and Delete a Tweet/Post/Twat and #102 Resolved Bug
  .github/ISSUE_TEMPLATE/user-story-issue-template.md
  .travis.yml
  Features.md
  README.md
  controllers/twatController.js
  models/twat.js
  names.md
  routes/twatRoute.js
  twatter-ui/src/app/app.module.ts
  twatter-ui/src/app/feed/posts/post-create/post-create.component.ts
  twatter-ui/src/app/feed/posts/post-list/post-edit-dialog.component.html
  twatter-ui/src/app/feed/posts/post-list/post-list.component.html
  twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
  twatter-ui/src/app/models/post.model.ts
  twatter-ui/src/app/services/post.service.ts
Labels: Back-End, Bug, Critical, Front-End, Task

#106 #52 #57 Minor visual changes
  twatter-ui/src/app/header/header.component.html
  twatter-ui/src/app/profile/sidebar/sidebar.component.html
  twatter-ui/src/app/profile/sidebar/sidebar.component.scss
Labels: Front-End, Normal, size:1

#109 #61 Fixed a bug where the posts subscribtion would be undefined.
  twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
Labels: Bug, Front-End

#112 #57 Aligned sidebar and posts in profile
  twatter-ui/src/app/profile/profile.component.html
  twatter-ui/src/app/profile/profile.component.scss
  twatter-ui/src/app/profile/sidebar/sidebar.component.scss
Labels: Front-End, Normal, Task

#114 #113 Fixed bug where the user's name would not display
  controllers/twatController.js
  controllers/user.js
  twatter-ui/src/app/feed/posts/post-create/post-create.component.ts
  twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
  twatter-ui/src/app/feed/twatline/twatline.component.html
  twatter-ui/src/app/feed/twatline/twatline.component.scss
  twatter-ui/src/app/feed/twatline/twatline.component.ts
  twatter-ui/src/app/header/header.component.html
  twatter-ui/src/app/models/post.model.ts
  twatter-ui/src/app/profile/profile.component.ts
  twatter-ui/src/app/services/post.service.ts
Labels: Bug, Critical, size:0

#116 #115 #93 Added Notification icon and post restrictions
  twatter-ui/src/app/feed/posts/post-list/post-list.component.html
  twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
  twatter-ui/src/app/header/header.component.html
  twatter-ui/src/app/header/header.component.scss
Labels: Front-End, Improvement, Normal, Task, size:0

#117 #61 Refactored app-header to be useful in all components
  twatter-ui/src/app/app.component.html
  twatter-ui/src/app/feed/twatline/twatline.component.html
  twatter-ui/src/app/header/header.component.scss
  twatter-ui/src/app/profile/profile.component.html
Labels: Front-End, Improvement, Low

#118 #58 Modified service and post create to sort tweets by timestamp
  controllers/twatController.js
  twatter-ui/src/app/feed/posts/post-create/post-create.component.ts
  twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
  twatter-ui/src/app/services/post.service.ts
Labels: Task, size:0

#119 #70 Modified Post Create
  twatter-ui/src/app/feed/posts/post-create/post-create-dialog.component.html
  twatter-ui/src/app/feed/posts/post-create/post-create.component.html
  twatter-ui/src/app/feed/posts/post-create/post-create.component.scss
  twatter-ui/src/app/feed/posts/post-create/post-create.component.ts
  twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
Labels: Front-End, Normal, Task, size:0

#120 #115 Updated Restrictions
  twatter-ui/src/app/feed/posts/post-create/post-create.component.ts
  twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
Labels: Front-End, Task, size:0

#121 #91 Added likes in post model
  twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
  twatter-ui/src/app/icons/twat-icon-btn/twat-icon-btn.component.ts
  twatter-ui/src/app/models/post.model.ts
  twatter-ui/src/app/services/post.service.ts
Labels: Front-End, Normal, Task, size:0

#122 #38 Upated post create, post list and post service to store likes
  twatter-ui/src/app/feed/posts/post-create/post-create.component.ts
  twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
  twatter-ui/src/app/models/post.model.ts
  twatter-ui/src/app/services/post.service.ts
Labels: Front-End, Normal, Task, size:0

#124 #82 #61 PR for notifications logic and some UI changes.
  .idea/Twatter.iml
  .idea/deployment.xml
  .idea/encodings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/webServers.xml
  .idea/workspace.xml
  twatter-ui/package.json
  twatter-ui/src/app/app.module.ts
  twatter-ui/src/app/feed/posts/post-create/post-create-dialog.component.html
  twatter-ui/src/app/feed/posts/post-create/post-create.component.html
  twatter-ui/src/app/feed/posts/post-list/post-edit-dialog.component.html
  twatter-ui/src/app/feed/posts/post-list/post-list.component.html
  twatter-ui/src/app/header/header.component.html
  twatter-ui/src/app/header/header.component.scss
  twatter-ui/src/app/header/header.component.ts
  twatter-ui/src/app/login/login.component.html
  twatter-ui/src/app/login/login.component.scss
  twatter-ui/src/assets/images/twatterLogo.png
  twatter-ui/src/index.html
Labels: Feature, Front-End

#125 Fixing Bug #126 Where elements in the header would not appear correctly.
  .idea/workspace.xml
  twatter-ui/src/app/app.module.ts
  twatter-ui/src/app/feed/posts/post-create/post-create.component.html
  twatter-ui/src/app/feed/posts/post-create/post-create.component.scss
  twatter-ui/src/app/feed/posts/post-list/post-list.component.html
  twatter-ui/src/app/header/header.component.html
  twatter-ui/src/app/header/header.component.scss
  twatter-ui/src/app/header/header.component.ts
  twatter-ui/src/app/profile/profile.component.scss
Labels: Bug, Front-End

#131 #97 Adding a search bar
  controllers/user.js
  twatter-ui/src/app/app-routing.module.ts
  twatter-ui/src/app/app.module.ts
  twatter-ui/src/app/header/header.component.html
  twatter-ui/src/app/header/header.component.scss
  twatter-ui/src/app/search-bar/search-bar.component.html
  twatter-ui/src/app/search-bar/search-bar.component.scss
  twatter-ui/src/app/search-bar/search-bar.component.spec.ts
  twatter-ui/src/app/search-bar/search-bar.component.ts
  twatter-ui/src/app/services/user.service.ts
Labels: Task

#136 #61 Remove idea from repo
  .idea/Twatter.iml
  .idea/deployment.xml
  .idea/encodings.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/webServers.xml
  .idea/workspace.xml
Labels: Bug, Critical

#135 #134, #55, #91: Added comments for post model, updated post route
  controllers/auth.js
  controllers/twatController.js
  controllers/user.js
  models/twat.js
  models/user.js
  routes/user.js
  twatter-ui/src/app/app.module.ts
  twatter-ui/src/app/feed/posts/comment/comment.component.html
  twatter-ui/src/app/feed/posts/comment/comment.component.ts
  twatter-ui/src/app/feed/posts/post-create/post-create.component.ts
  twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
  twatter-ui/src/app/models/post.model.ts
  twatter-ui/src/app/services/post.service.ts
Labels: Back-End

#151 #72 #145 #148 Search a User/Post
  controllers/twatController.js
  routes/twatRoute.js
  twatter-ui/package.json
  twatter-ui/src/app/app-routing.module.ts
  twatter-ui/src/app/app.module.ts
  twatter-ui/src/app/header/header.component.html
  twatter-ui/src/app/header/header.component.scss
  twatter-ui/src/app/search-bar/search-bar.component.html
  twatter-ui/src/app/search-bar/search-bar.component.scss
  twatter-ui/src/app/search-bar/search-bar.component.ts
  twatter-ui/src/app/search/search-bar/search-bar.component.html
  twatter-ui/src/app/search/search-bar/search-bar.component.scss
  twatter-ui/src/app/search/search-bar/search-bar.component.spec.ts
  twatter-ui/src/app/search/search-bar/search-bar.component.ts
  twatter-ui/src/app/search/search-results/search-results.component.html
  twatter-ui/src/app/search/search-results/search-results.component.scss
  twatter-ui/src/app/search/search-results/search-results.component.ts
  twatter-ui/src/app/services/post.service.ts
  twatter-ui/src/app/services/user.service.ts
  twatter-ui/src/assets/images/baseline-search-24px.svg
Labels: Back-End, Front-End, Normal, size:3

#139 #128 UI for user to change their info
  .idea/inspectionProfiles/Project_Default.xml
  .idea/vcs.xml
  controllers/user.js
  twatter-ui/package.json
  twatter-ui/src/app/app-routing.module.ts
  twatter-ui/src/app/app.module.ts
  twatter-ui/src/app/feed/posts/comment/comment.component.html
  twatter-ui/src/app/feed/posts/comment/comment.component.scss
  twatter-ui/src/app/feed/posts/comment/comment.component.spec.ts
  twatter-ui/src/app/feed/posts/comment/comment.component.ts
  twatter-ui/src/app/feed/posts/post-create/post-create-dialog.component.html
  twatter-ui/src/app/feed/posts/post-create/post-create.component.html
  twatter-ui/src/app/feed/posts/post-create/post-create.component.scss
  twatter-ui/src/app/feed/posts/post-list/post-edit-dialog.component.html
  twatter-ui/src/app/feed/posts/post-list/post-list.component.html
  twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
  twatter-ui/src/app/header/header.component.html
  twatter-ui/src/app/header/header.component.scss
  twatter-ui/src/app/header/header.component.ts
  twatter-ui/src/app/login/login.component.html
  twatter-ui/src/app/login/login.component.scss
  twatter-ui/src/app/models/comment.model.ts
  twatter-ui/src/app/models/post.model.ts
  twatter-ui/src/app/profile/profile.component.scss
  twatter-ui/src/app/register/register.component.ts
  twatter-ui/src/app/search-bar/search-bar.component.html
  twatter-ui/src/app/search-bar/search-bar.component.scss
  twatter-ui/src/app/search-bar/search-bar.component.spec.ts
  twatter-ui/src/app/search-bar/search-bar.component.ts
  twatter-ui/src/app/services/notification.service.spec.ts
  twatter-ui/src/app/services/notification.service.ts
  twatter-ui/src/app/services/post.service.ts
  twatter-ui/src/app/services/user.service.ts
  twatter-ui/src/app/settings/settings.component.html
  twatter-ui/src/app/settings/settings.component.scss
  twatter-ui/src/app/settings/settings.component.spec.ts
  twatter-ui/src/app/settings/settings.component.ts
  twatter-ui/src/app/settings/sidebar-settings/sidebar-settings.component.html
  twatter-ui/src/app/settings/sidebar-settings/sidebar-settings.component.scss
  twatter-ui/src/app/settings/sidebar-settings/sidebar-settings.component.spec.ts
  twatter-ui/src/app/settings/sidebar-settings/sidebar-settings.component.ts
  twatter-ui/src/assets/images/twatterLogo.png
  twatter-ui/src/index.html
Labels: Front-End, Improvement, Normal

#155 #129 user story comment (Second one didn't work as well)
  README.md
  twatter-ui/package.json
  twatter-ui/src/app/app-routing.module.ts
  twatter-ui/src/app/app.module.ts
  twatter-ui/src/app/header/header.component.html
  twatter-ui/src/app/header/header.component.scss
  twatter-ui/src/app/register/register.component.ts
  twatter-ui/src/app/services/user.service.ts
  twatter-ui/src/app/settings/settings.component.html
  twatter-ui/src/app/settings/settings.component.scss
  twatter-ui/src/app/settings/settings.component.spec.ts
  twatter-ui/src/app/settings/settings.component.ts
  twatter-ui/src/app/settings/sidebar-settings/sidebar-settings.component.html
  twatter-ui/src/app/settings/sidebar-settings/sidebar-settings.component.scss
  twatter-ui/src/app/settings/sidebar-settings/sidebar-settings.component.spec.ts
  twatter-ui/src/app/settings/sidebar-settings/sidebar-settings.component.ts
Labels: User Story

#159 #158 Update issue templates
  .github/ISSUE_TEMPLATE/user-story-acceptance-test-template.md
  .github/ISSUE_TEMPLATE/user-story-issue-template.md
Labels: Improvement

#162 #158 Update issue templates
  .github/ISSUE_TEMPLATE/user-story-acceptance-test-template.md
Labels: Improvement

#160 #143 #144 Can modify comments
  twatter-ui/src/app/feed/posts/comment/comment.component.html
  twatter-ui/src/app/feed/posts/comment/comment.component.scss
  twatter-ui/src/app/feed/posts/comment/comment.component.ts
  twatter-ui/src/app/feed/posts/post-list/post-list.component.html
  twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
Labels: Front-End, Normal, Task

#169 #164 #165 #166 Access other user's profile
  twatter-ui/src/app/app-routing.module.ts
  twatter-ui/src/app/feed/posts/post-list/post-list.component.html
  twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
  twatter-ui/src/app/header/header.component.html
  twatter-ui/src/app/header/header.component.ts
  twatter-ui/src/app/profile/profile.component.scss
  twatter-ui/src/app/profile/profile.component.ts
  twatter-ui/src/app/profile/sidebar/sidebar.component.html
  twatter-ui/src/app/profile/sidebar/sidebar.component.ts
  twatter-ui/src/app/services/user.service.ts
Labels: Front-End, Normal

#170 #148 Modified search results and #61 minor styling .
  controllers/twatController.js
  controllers/user.js
  twatter-ui/package.json
  twatter-ui/src/app/app.component.scss
  twatter-ui/src/app/app.module.ts
  twatter-ui/src/app/feed/posts/comment/comment.component.html
  twatter-ui/src/app/feed/posts/post-list/post-list.component.html
  twatter-ui/src/app/feed/posts/post-list/post-list.component.scss
  twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
  twatter-ui/src/app/header/header.component.scss
  twatter-ui/src/app/header/header.component.ts
  twatter-ui/src/app/icons/twat-icon-btn/twat-icon-btn.component.html
  twatter-ui/src/app/icons/twat-icon-btn/twat-icon-btn.component.scss
  twatter-ui/src/app/icons/twat-icon-btn/twat-icon-btn.component.ts
  twatter-ui/src/app/profile/profile.component.ts
  twatter-ui/src/app/search/search-bar/search-bar.component.ts
  twatter-ui/src/app/search/search-results/search-results.component.html
  twatter-ui/src/app/search/search-results/search-results.component.scss
  twatter-ui/src/app/search/search-results/search-results.component.ts
  twatter-ui/src/app/services/user.service.ts
  twatter-ui/src/styles.scss
  twatter-ui/src/twatter-default-style.scss
Labels: Front-End, Improvement, Normal, Task
